/// TokenType represents token
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum TokenType {
    /// System
    StartToken,
    Illegal(String),
    EOF,

    /// Synbol Char
    Ampersand,   // &
    AtMark,      // @
    Ast,         // *
    Bang,        // !
    Colon,       // :
    Comma,       // ,
    DollerSign,  // $
    DoubleQuote, // "
    EqOp,        // =
    EqEqOp             // ==
    GreaterOp,   // >
    GraterThanEqOp,             // >=
    LeftBra,     // [
    LeftBrace,   // {
    LeftShiftOp,             // <<
    LessOp,      // <
    LessThanEqOp,             // <=
    Lparen,      // (
    Minus,       // -
    NotEqOp             // !=
    Percent,     // %
    Period,      // .
    Plus,        // +
    Quote,       // '
    Rparen,      // )
    RightBra,    // ]
    RightBrace,  // }
    RightShiftOp,             // >>
    SemiColon,   // ;
    Slash,       // /
    UnderScore,  // _
    VerticalBar, // |

    /// Literal
    Ident(String), // a~z, A~Z, 0~ 9
    Number(i64), // 0 ~ 9
    Bool(bool),  // true or false
    // TODO: Float(f64),  // float

    /// Referenced pingcap/parser
    /// https://github.com/pingcap/parser/blob/master/parser.y
    ///
    /// The following tokens belong to ReservedKeyword. Notice: make sure these tokens are contained in ReservedKeyword.
    Add, // "ADD"
    All,               // "ALL"
    Alter,             // "ALTER"
    Analyze,           // "ANALYZE"
    And,               // "AND"
    As,                // "AS"
    Asc,               // "ASC"
    Between,           // "BETWEEN"
    BigIntType,        // "BIGINT"
    BinaryType,        // "BINARY"
    BlobType,          // "BLOB"
    Both,              // "BOTH"
    By,                // "BY"
    Call,              // "CALL"
    Cascade,           // "CASCADE"
    CaseKwd,           // "CASE"
    Change,            // "CHANGE"
    Character,         // "CHARACTER"
    CharType,          // "CHAR"
    Check,             // "CHECK"
    Collate,           // "COLLATE"
    Column,            // "COLUMN"
    Constraint,        // "CONSTRAINT"
    Convert,           // "CONVERT"
    Create,            // "CREATE"
    Cross,             // "CROSS"
    CumeDist,          // "CUME_DIST"
    CurrentDate,       // "CURRENT_DATE"
    CurrentTime,       // "CURRENT_TIME"
    CurrentTs,         // "CURRENT_TIMESTAMP"
    CurrentUser,       // "CURRENT_USER"
    CurrentRole,       // "CURRENT_ROLE"
    Database,          // "DATABASE"
    Databases,         // "DATABASES"
    DayHour,           // "DAY_HOUR"
    DayMicrosecond,    // "DAY_MICROSECOND"
    DayMinute,         // "DAY_MINUTE"
    DaySecond,         // "DAY_SECOND"
    DecimalType,       // "DECIMAL"
    DefaultKwd,        // "DEFAULT"
    Delayed,           // "DELAYED"
    DeleteKwd,         // "DELETE"
    DenseRank,         // "DENSE_RANK"
    Desc,              // "DESC"
    Describe,          // "DESCRIBE"
    Distinct,          // "DISTINCT"
    DistinctRow,       // "DISTINCTROW"
    Div,               // "DIV"
    DoubleType,        // "DOUBLE"
    Drop,              // "DROP"
    Dual,              // "DUAL"
    ElseKwd,           // "ELSE"
    Enclosed,          // "ENCLOSED"
    Escaped,           // "ESCAPED"
    Exists,            // "EXISTS"
    Explain,           // "EXPLAIN"
    Except,            // "EXCEPT"
    FalseKwd,          // "FALSE"
    Fetch,             // "FETCH"
    FirstValue,        // "FIRST_VALUE"
    FloatType,         // "FLOAT"
    ForKwd,            // "FOR"
    Force,             // "FORCE"
    Foreign,           // "FOREIGN"
    From,              // "FROM"
    Fulltext,          // "FULLTEXT"
    Generated,         // "GENERATED"
    Grant,             // "GRANT"
    Group,             // "GROUP"
    Groups,            // "GROUPS"
    Having,            // "HAVING"
    HighPriority,      // "HIGH_PRIORITY"
    HourMicrosecond,   // "HOUR_MICROSECOND"
    HourMinute,        // "HOUR_MINUTE"
    HourSecond,        // "HOUR_SECOND"
    IfKwd,             // "IF"
    Ignore,            // "IGNORE"
    In,                // "IN"
    Index,             // "INDEX"
    Infile,            // "INFILE"
    Inner,             // "INNER"
    IntegerType,       // "INTEGER"
    Intersect,         // "INTERSECT"
    Interval,          // "INTERVAL"
    Into,              // "INTO"
    Outfile,           // "OUTFILE"
    Is,                // "IS"
    Insert,            // "INSERT"
    IntType,           // "INT"
    Int1Type,          // "INT1"
    Int2Type,          // "INT2"
    Int3Type,          // "INT3"
    Int4Type,          // "INT4"
    Int8Type,          // "INT8"
    Join,              // "JOIN"
    Key,               // "KEY"
    Keys,              // "KEYS"
    Kill,              // "KILL"
    Lag,               // "LAG"
    LastValue,         // "LAST_VALUE"
    Lead,              // "LEAD"
    Leading,           // "LEADING"
    Left,              // "LEFT"
    Like,              // "LIKE"
    Limit,             // "LIMIT"
    Lines,             // "LINES"
    Linear,            // "LINEAR"
    Load,              // "LOAD"
    LocalTime,         // "LOCALTIME"
    LocalTs,           // "LOCALTIMESTAMP"
    Lock,              // "LOCK"
    LongblobType,      // "LONGBLOB"
    LongtextType,      // "LONGTEXT"
    LowPriority,       // "LOW_PRIORITY"
    Match,             // "MATCH"
    MaxValue,          // "MAXVALUE"
    MediumblobType,    // "MEDIUMBLOB"
    MediumIntType,     // "MEDIUMINT"
    MediumtextType,    // "MEDIUMTEXT"
    MinuteMicrosecond, // "MINUTE_MICROSECOND"
    MinuteSecond,      // "MINUTE_SECOND"
    Mod,               // "MOD"
    Not,               // "NOT"
    NoWriteToBinLog,   // "NO_WRITE_TO_BINLOG"
    NthValue,          // "NTH_VALUE"
    Ntile,             // "NTILE"
    Null,              // "NULL"
    NumericType,       // "NUMERIC"
    Of,                // "OF"
    On,                // "ON"
    Optimize,          // "OPTIMIZE"
    Option,            // "OPTION"
    Optionally,        // "OPTIONALLY"
    Or,                // "OR"
    Order,             // "ORDER"
    Outer,             // "OUTER"
    Over,              // "OVER"
    Partition,         // "PARTITION"
    PercentRank,       // "PERCENT_RANK"
    PrecisionType,     // "PRECISION"
    Primary,           // "PRIMARY"
    Procedure,         // "PROCEDURE"
    RangeKwd,          // "RANGE"
    Rank,              // "RANK"
    Read,              // "READ"
    RealType,          // "REAL"
    Recursive,         // "RECURSIVE"
    References,        // "REFERENCES"
    RegexpKwd,         // "REGEXP"
    Release,           // "RELEASE"
    Rename,            // "RENAME"
    Repeat,            // "REPEAT"
    Replace,           // "REPLACE"
    Require,           // "REQUIRE"
    Restrict,          // "RESTRICT"
    Revoke,            // "REVOKE"
    Right,             // "RIGHT"
    Rlike,             // "RLIKE"
    Row,               // "ROW"
    Rows,              // "ROWS"
    RowNumber,         // "ROW_NUMBER"
    SecondMicrosecond, // "SECOND_MICROSECOND"
    SelectKwd,         // "SELECT"
    Set,               // "SET"
    Show,              // "SHOW"
    SmallIntType,      // "SMALLINT"
    Spatial,           // "SPATIAL"
    Sql,               // "SQL"
    SqlBigResult,      // "SQL_BIG_RESULT"
    SqlCalcFoundRows,  // "SQL_CALC_FOUND_ROWS"
    SqlSmallResult,    // "SQL_SMALL_RESULT"
    Ssl,               // "SSL"
    Starting,          // "STARTING"
    StatsExtended,     // "STATS_EXTENDED"
    StraightJoin,      // "STRAIGHT_JOIN"
    TableKwd,          // "TABLE"
    TableSample,       // "TABLESAMPLE"
    Stored,            // "STORED"
    Terminated,        // "TERMINATED"
    Then,              // "THEN"
    TinyblobType,      // "TINYBLOB"
    TinyIntType,       // "TINYINT"
    TinytextType,      // "TINYTEXT"
    To,                // "TO"
    Trailing,          // "TRAILING"
    Trigger,           // "TRIGGER"
    TrueKwd,           // "TRUE"
    Unique,            // "UNIQUE"
    Union,             // "UNION"
    Unlock,            // "UNLOCK"
    Unsigned,          // "UNSIGNED"
    Update,            // "UPDATE"
    Usage,             // "USAGE"
    Use,               // "USE"
    Using,             // "USING"
    UtcDate,           // "UTC_DATE"
    UtcTimestamp,      // "UTC_TIMESTAMP"
    UtcTime,           // "UTC_TIME"
    Values,            // "VALUES"
    Long,              // "LONG"
    VarcharType,       // "VARCHAR"
    Varcharacter,      // "VARCHARACTER"
    VarbinaryType,     // "VARBINARY"
    Varying,           // "VARYING"
    Virtual,           // "VIRTUAL"
    When,              // "WHEN"
    Where,             // "WHERE"
    Write,             // "WRITE"
    Window,            // "WINDOW"
    With,              // "WITH"
    Xor,               // "XOR"
    YearMonth,         // "YEAR_MONTH"
    Zerofill,          // "ZEROFILL"
    Natural,           // "NATURAL"

    /* The following tokens belong to UnReservedKeyword. Notice: make sure these tokens are contained in UnReservedKeyword. */
    Account,               // "ACCOUNT"
    Action,                // "ACTION"
    Advise,                // "ADVISE"
    After,                 // "AFTER"
    Against,               // "AGAINST"
    Ago,                   // "AGO"
    Algorithm,             // "ALGORITHM"
    Always,                // "ALWAYS"
    Any,                   // "ANY"
    Ascii,                 // "ASCII"
    Attributes,            // "ATTRIBUTES"
    AutoIdCache,           // "AUTO_ID_CACHE"
    AutoIncrement,         // "AUTO_INCREMENT"
    AutoRandom,            // "AUTO_RANDOM"
    AutoRandomBase,        // "AUTO_RANDOM_BASE"
    Avg,                   // "AVG"
    AvgRowLength,          // "AVG_ROW_LENGTH"
    Backend,               // "BACKEND"
    Backup,                // "BACKUP"
    Backups,               // "BACKUPS"
    Begin,                 // "BEGIN"
    Bernoulli,             // "BERNOULLI"
    Binding,               // "BINDING"
    Bindings,              // "BINDINGS"
    Binlog,                // "BINLOG"
    BitType,               // "BIT"
    Block,                 // "BLOCK"
    BooleanType,           // "BOOLEAN"
    BoolType,              // "BOOL"
    Btree,                 // "BTREE"
    ByteType,              // "BYTE"
    Cache,                 // "CACHE"
    Capture,               // "CAPTURE"
    Cascaded,              // "CASCADED"
    Causal,                // "CAUSAL"
    Chain,                 // "CHAIN"
    CharsetKwd,            // "CHARSET"
    Checkpoint,            // "CHECKPOINT"
    Checksum,              // "CHECKSUM"
    Cipher,                // "CIPHER"
    Cleanup,               // "CLEANUP"
    Client,                // "CLIENT"
    ClientErrorsSummary,   // "CLIENT_ERRORS_SUMMARY"
    Coalesce,              // "COALESCE"
    Collation,             // "COLLATION"
    ColumnFormat,          // "COLUMN_FORMAT"
    Columns,               // "COLUMNS"
    Config,                // "CONFIG"
    Comment,               // "COMMENT"
    Commit,                // "COMMIT"
    Committed,             // "COMMITTED"
    Compact,               // "COMPACT"
    Compressed,            // "COMPRESSED"
    Compression,           // "COMPRESSION"
    Concurrency,           // "CONCURRENCY"
    Connection,            // "CONNECTION"
    Consistency,           // "CONSISTENCY"
    Consistent,            // "CONSISTENT"
    Context,               // "CONTEXT"
    Cpu,                   // "CPU"
    CsvBackslashEscape,    // "CSV_BACKSLASH_ESCAPE"
    CsvDelimiter,          // "CSV_DELIMITER"
    CsvHeader,             // "CSV_HEADER"
    CsvNotNull,            // "CSV_NOT_NULL"
    CsvNull,               // "CSV_NULL"
    CsvSeparator,          // "CSV_SEPARATOR"
    CsvTrimLastSeparators, // "CSV_TRIM_LAST_SEPARATORS"
    Current,               // "CURRENT"
    Clustered,             // "CLUSTERED"
    Cycle,                 // "CYCLE"
    Data,                  // "DATA"
    DatetimeType,          // "DATETIME"
    DateType,              // "DATE"
    Day,                   // "DAY"
    Deallocate,            // "DEALLOCATE"
    Definer,               // "DEFINER"
    DelayKeyWrite,         // "DELAY_KEY_WRITE"
    Directory,             // "DIRECTORY"
    Disable,               // "DISABLE"
    Discard,               // "DISCARD"
    Disk,                  // "DISK"
    Do,                    // "DO"
    Duplicate,             // "DUPLICATE"
    Dynamic,               // "DYNAMIC"
    Enable,                // "ENABLE"
    Encryption,            // "ENCRYPTION"
    End,                   // "END"
    Enforced,              // "ENFORCED"
    Engine,                // "ENGINE"
    Engines,               // "ENGINES"
    Enum,                  // "ENUM"
    ErrorKwd,              // "ERROR"
    Escape,                // "ESCAPE"
    Event,                 // "EVENT"
    Events,                // "EVENTS"
    Evolve,                // "EVOLVE"
    Exchange,              // "EXCHANGE"
    Exclusive,             // "EXCLUSIVE"
    Execute,               // "EXECUTE"
    Expansion,             // "EXPANSION"
    Expire,                // "EXPIRE"
    Extended,              // "EXTENDED"
    FaultsSym,             // "FAULTS"
    Fields,                // "FIELDS"
    File,                  // "FILE"
    First,                 // "FIRST"
    Fixed,                 // "FIXED"
    Flush,                 // "FLUSH"
    Following,             // "FOLLOWING"
    Format,                // "FORMAT"
    Full,                  // "FULL"
    Function,              // "FUNCTION"
    General,               // "GENERAL"
    Global,                // "GLOBAL"
    Grants,                // "GRANTS"
    Hash,                  // "HASH"
    Help,                  // "HELP"
    Histogram,             // "HISTOGRAM"
    History,               // "HISTORY"
    Hosts,                 // "HOSTS"
    Hour,                  // "HOUR"
    Identified,            // "IDENTIFIED"
    IdentSQLErrors,        // "ERRORS"
    ImportKwd,             // "IMPORT"
    Imports,               // "IMPORTS"
    Increment,             // "INCREMENT"
    Incremental,           // "INCREMENTAL"
    Indexes,               // "INDEXES"
    InsertMethod,          // "INSERT_METHOD"
    Instance,              // "INSTANCE"
    Invisible,             // "INVISIBLE"
    Invoker,               // "INVOKER"
    Io,                    // "IO"
    Ipc,                   // "IPC"
    Isolation,             // "ISOLATION"
    Issuer,                // "ISSUER"
    JsonType,              // "JSON"
    KeyBlockSize,          // "KEY_BLOCK_SIZE"
    Labels,                // "LABELS"
    Language,              // "LANGUAGE"
    Last,                  // "LAST"
    LastBackup,            // "LAST_BACKUP"
    Lastval,               // "LASTVAL"
    Less,                  // "LESS"
    Level,                 // "LEVEL"
    List,                  // "LIST"
    Local,                 // "LOCAL"
    Locked,                // "LOCKED"
    Location,              // "LOCATION"
    Logs,                  // "LOGS"
    Master,                // "MASTER"
    MaxIdxnum,             // "MAX_IDXNUM"
    MaxMinutes,            // "MAX_MINUTES"
    MaxConnectionsPerHour, // "MAX_CONNECTIONS_PER_HOUR"
    MaxQueriesPerHour,     // "MAX_QUERIES_PER_HOUR"
    MaxRows,               // "MAX_ROWS"
    MaxUpdatesPerHour,     // "MAX_UPDATES_PER_HOUR"
    MaxUserConnections,    // "MAX_USER_CONNECTIONS"
    Mb,                    // "MB"
    Memory,                // "MEMORY"
    Merge,                 // "MERGE"
    Microsecond,           // "MICROSECOND"
    MinRows,               // "MIN_ROWS"
    Minute,                // "MINUTE"
    MinValue,              // "MINVALUE"
    Mode,                  // "MODE"
    Modify,                // "MODIFY"
    Month,                 // "MONTH"
    Names,                 // "NAMES"
    National,              // "NATIONAL"
    NcharType,             // "NCHAR"
    Never,                 // "NEVER"
    Next,                  // "NEXT"
    Nextval,               // "NEXTVAL"
    No,                    // "NO"
    Nocache,               // "NOCACHE"
    Nocycle,               // "NOCYCLE"
    Nodegroup,             // "NODEGROUP"
    Nomaxvalue,            // "NOMAXVALUE"
    Nominvalue,            // "NOMINVALUE"
    Nonclustered,          // "NONCLUSTERED"
    None,                  // "NONE"
    Nowait,                // "NOWAIT"
    NvarcharType,          // "NVARCHAR"
    Nulls,                 // "NULLS"
    Off,                   // "OFF"
    Offset,                // "OFFSET"
    OnDuplicate,           // "ON_DUPLICATE"
    Online,                // "ONLINE"
    Only,                  // "ONLY"
    Open,                  // "OPEN"
    Optional,              // "OPTIONAL"
    PackKeys,              // "PACK_KEYS"
    PageSym,               // "PAGE"
    Parser,                // "PARSER"
    Partial,               // "PARTIAL"
    Partitioning,          // "PARTITIONING"
    Partitions,            // "PARTITIONS"
    Password,              // "PASSWORD"
    // TODO: Percent,               // "PERCENT"
    PerDB,    // "PER_DB"
    PerTable, // "PER_TABLE"
    PipesAsOr,
    Plugins,               // "PLUGINS"
    Policy,                // "POLICY"
    PreSplitRegions,       // "PRE_SPLIT_REGIONS"
    Preceding,             // "PRECEDING"
    Prepare,               // "PREPARE"
    Preserve,              // "PRESERVE"
    Privileges,            // "PRIVILEGES"
    Process,               // "PROCESS"
    Processlist,           // "PROCESSLIST"
    Profile,               // "PROFILE"
    Profiles,              // "PROFILES"
    Proxy,                 // "PROXY"
    Purge,                 // "PURGE"
    Quarter,               // "QUARTER"
    Queries,               // "QUERIES"
    Query,                 // "QUERY"
    Quick,                 // "QUICK"
    RateLimit,             // "RATE_LIMIT"
    Rebuild,               // "REBUILD"
    Recover,               // "RECOVER"
    Redundant,             // "REDUNDANT"
    Reload,                // "RELOAD"
    Remove,                // "REMOVE"
    Reorganize,            // "REORGANIZE"
    Repair,                // "REPAIR"
    Repeatable,            // "REPEATABLE"
    Replica,               // "REPLICA"
    Replicas,              // "REPLICAS"
    Replication,           // "REPLICATION"
    Required,              // "REQUIRED"
    Respect,               // "RESPECT"
    Restart,               // "RESTART"
    Restore,               // "RESTORE"
    Restores,              // "RESTORES"
    Resume,                // "RESUME"
    Reverse,               // "REVERSE"
    Role,                  // "ROLE"
    Rollback,              // "ROLLBACK"
    Routine,               // "ROUTINE"
    RowCount,              // "ROW_COUNT"
    RowFormat,             // "ROW_FORMAT"
    Rtree,                 // "RTREE"
    San,                   // "SAN"
    Second,                // "SECOND"
    SecondaryEngine,       // "SECONDARY_ENGINE"
    SecondaryLoad,         // "SECONDARY_LOAD"
    SecondaryUnload,       // "SECONDARY_UNLOAD"
    Security,              // "SECURITY"
    SendCredentialsToTiKV, // "SEND_CREDENTIALS_TO_TIKV"
    Separator,             // "SEPARATOR"
    Sequence,              // "SEQUENCE"
    Serial,                // "SERIAL"
    Serializable,          // "SERIALIZABLE"
    Session,               // "SESSION"
    Setval,                // "SETVAL"
    ShardRowIDBits,        // "SHARD_ROW_ID_BITS"
    Share,                 // "SHARE"
    Shared,                // "SHARED"
    Shutdown,              // "SHUTDOWN"
    Signed,                // "SIGNED"
    Simple,                // "SIMPLE"
    Skip,                  // "SKIP"
    SkipSchemaFiles,       // "SKIP_SCHEMA_FILES"
    Slave,                 // "SLAVE"
    Slow,                  // "SLOW"
    Snapshot,              // "SNAPSHOT"
    Some,                  // "SOME"
    Source,                // "SOURCE"
    SqlBufferResult,       // "SQL_BUFFER_RESULT"
    SqlCache,              // "SQL_CACHE"
    SqlNoCache,            // "SQL_NO_CACHE"
    SqlTsiDay,             // "SQL_TSI_DAY"
    SqlTsiHour,            // "SQL_TSI_HOUR"
    SqlTsiMinute,          // "SQL_TSI_MINUTE"
    SqlTsiMonth,           // "SQL_TSI_MONTH"
    SqlTsiQuarter,         // "SQL_TSI_QUARTER"
    SqlTsiSecond,          // "SQL_TSI_SECOND"
    SqlTsiWeek,            // "SQL_TSI_WEEK"
    SqlTsiYear,            // "SQL_TSI_YEAR"
    Start,                 // "START"
    StatsAutoRecalc,       // "STATS_AUTO_RECALC"
    StatsPersistent,       // "STATS_PERSISTENT"
    StatsSamplePages,      // "STATS_SAMPLE_PAGES"
    Status,                // "STATUS"
    Storage,               // "STORAGE"
    StrictFormat,          // "STRICT_FORMAT"
    Subject,               // "SUBJECT"
    Subpartition,          // "SUBPARTITION"
    Subpartitions,         // "SUBPARTITIONS"
    Super,                 // "SUPER"
    Swaps,                 // "SWAPS"
    SwitchesSym,           // "SWITCHES"
    System,                // "SYSTEM"
    SystemTime,            // "SYSTEM_TIME"
    TableChecksum,         // "TABLE_CHECKSUM"
    Tables,                // "TABLES"
    Tablespace,            // "TABLESPACE"
    Temporary,             // "TEMPORARY"
    Temptable,             // "TEMPTABLE"
    TextType,              // "TEXT"
    Than,                  // "THAN"
    TikvImporter,          // "TIKV_IMPORTER"
    TimestampType,         // "TIMESTAMP"
    TimeType,              // "TIME"
    Tp,                    // "TYPE"
    Trace,                 // "TRACE"
    Traditional,           // "TRADITIONAL"
    Transaction,           // "TRANSACTION"
    Triggers,              // "TRIGGERS"
    Truncate,              // "TRUNCATE"
    Unbounded,             // "UNBOUNDED"
    Uncommitted,           // "UNCOMMITTED"
    Undefined,             // "UNDEFINED"
    UnicodeSym,            // "UNICODE"
    Unknown,               // "UNKNOWN"
    User,                  // "USER"
    Validation,            // "VALIDATION"
    Value,                 // "VALUE"
    Variables,             // "VARIABLES"
    View,                  // "VIEW"
    Visible,               // "VISIBLE"
    Warnings,              // "WARNINGS"
    Week,                  // "WEEK"
    WeightString,          // "WEIGHT_STRING"
    Without,               // "WITHOUT"
    X509,                  // "X509"
    YearType,              // "YEAR"
    Wait,                  // "WAIT"

    /* The following tokens belong to NotKeywordToken. Notice: make sure these tokens are contained in NotKeywordToken. */
    AddDate,               //"ADDDATE"
    ApproxCountDistinct,   //"APPROX_COUNT_DISTINCT"
    ApproxPercentile,      //"APPROX_PERCENTILE"
    BitAnd,                //"BIT_AND"
    BitOr,                 //"BIT_OR"
    BitXor,                //"BIT_XOR"
    Bound,                 //"BOUND"
    BriefType,             //"BRIEF"
    Cast,                  //"CAST"
    CopyKwd,               //"COPY"
    Constraints,           //"CONSTRAINTS"
    CurTime,               //"CURTIME"
    DateAdd,               //"DATE_ADD"
    DateSub,               //"DATE_SUB"
    DotType,               //"DOT"
    Dump,                  //"DUMP"
    Exact,                 //"EXACT"
    ExprPushdownBlacklist, //"EXPR_PUSHDOWN_BLACKLIST"
    Extract,               //"EXTRACT"
    Flashback,             //"FLASHBACK"
    Follower,              //"FOLLOWER"
    FollowerConstraints,   //"FOLLOWER_CONSTRAINTS"
    Followers,             //"FOLLOWERS"
    GetFormat,             //"GET_FORMAT"
    GroupConcat,           //"GROUP_CONCAT"
    NextRowID,             //"NEXT_ROW_ID"
    Inplace,               //"INPLACE"
    Instant,               //"INSTANT"
    Internal,              //"INTERNAL"
    JsonArrayagg,          //"JSON_ARRAYAGG"
    JsonObjectAgg,         //"JSON_OBJECTAGG"
    Leader,                //"LEADER"
    LeaderConstraints,     //"LEADER_CONSTRAINTS"
    Learner,               //"LEARNER"
    LearnerConstraints,    //"LEARNER_CONSTRAINTS"
    Learners,              //"LEARNERS"
    Min,                   //"MIN"
    Max,                   //"MAX"
    Now,                   //"NOW"
    OptRuleBlacklist,      //"OPT_RULE_BLACKLIST"
    Placement,             //"PLACEMENT"
    Plan,                  //"PLAN"
    Position,              //"POSITION"
    PrimaryRegion,         //"PRIMARY_REGION"
    Recent,                //"RECENT"
    Recreator,             //"RECREATOR"
    Running,               //"RUNNING"
    S3,                    //"S3"
    Schedule,              //"SCHEDULE"
    Staleness,             //"STALENESS"
    Std,                   //"STD"
    Stddev,                //"STDDEV"
    StddevPop,             //"STDDEV_POP"
    StddevSamp,            //"STDDEV_SAMP"
    Stop,                  //"STOP"
    Strict,                //"STRICT"
    Strong,                //"STRONG"
    SubDate,               //"SUBDATE"
    Sum,                   //"SUM"
    Substring,             //"SUBSTRING"
    TimestampAdd,          //"TIMESTAMPADD"
    TimestampDiff,         //"TIMESTAMPDIFF"
    Tls,                   //"TLS"
    TokudbDefault,         //"TOKUDB_DEFAULT"
    TokudbFast,            //"TOKUDB_FAST"
    TokudbLzma,            //"TOKUDB_LZMA"
    TokudbQuickLZ,         //"TOKUDB_QUICKLZ"
    TokudbSnappy,          //"TOKUDB_SNAPPY"
    TokudbSmall,           //"TOKUDB_SMALL"
    TokudbUncompressed,    //"TOKUDB_UNCOMPRESSED"
    TokudbZlib,            //"TOKUDB_ZLIB"
    Top,                   //"TOP"
    Trim,                  //"TRIM"
    Variance,              //"VARIANCE"
    VarPop,                //"VAR_POP"
    VarSamp,               //"VAR_SAMP"
    VerboseType,           //"VERBOSE"
    Voter,                 //"VOTER"
    VoterConstraints,      //"VOTER_CONSTRAINTS"
    Voters,                //"VOTERS"
}
